# Generated by Django 5.2.4 on 2025-07-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_order_created_at_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-ordered_at']},
        ),
    ]
